env:
  variables:
    NODE_ENV: development
    PORT: "3000"
    HOST: 0.0.0.0
    CORS_ORIGIN: "*"
    SESSION_SECRET: your-super-secret-session-key-here
    LOG_LEVEL: "info"
    LOG_FORMAT: "combined"
    ENABLE_HEALTH_CHECKS: "true"
    ENABLE_METRICS: "true"
    ENABLE_DETAILED_ERRORS: "false"
